name: accubooks
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  git: ^2.2.1
  get: ^4.6.6
  flutter_slidable: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  iconify: ^0.0.1
  font_awesome_icon_class: ^0.0.6
  animated_theme_switcher: ^2.0.10
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  barcode_scanner: ^3.6.2
  flutter_barcode_scanner: ^2.0.0
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.66.2
  pie_chart: ^5.4.0
  syncfusion_flutter_charts: ^24.2.8
  image_picker: ^1.0.7
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
   - icons/
  fonts:
     - family: Yekan
       fonts:
         - asset: fonts/Yekan.ttf
     - family: YekanBakh
       fonts:
        - asset: fonts/YekanBakh.ttf
     - family: Vazirmatn
       fonts:
        - asset: fonts/Vazirmatn.ttf
     - family: IRANSansX
       fonts:
        - asset: fonts/IRANSansX.ttf
